apiVersion: v1
kind: Service
metadata:
  name: kowl
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kowl
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowl
spec:
  selector:
    matchLabels:
      app: kowl
  replicas: 1
  template:
    metadata:
      labels:
        app: kowl
    spec:
      containers:
      - name: kowl
        image: quay.io/cloudhut/kowl:master
        env:
        - name: KAFKA_BROKERS
          value: my-cluster-kafka-external3-bootstrap:9094
